server:
  port: 9101

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: "demo"
  datasource:
    url: "jdbc:postgresql://localhost:5432/demo"
    username: "demo"
    password: "root"